### ISSUE TITLE
Update gradle to latest version

### ISSUE THREAD

**Issue by apete** [lessthanoptimal/Java-Matrix-Benchmark#18]
Importing the modules/projects to eclipse doesn't work, and the gradle project import wizard does present a list of various features that will not work because of the old version used.

Building on the command line works fine.

I tried just replacing the version with a newer one, but that didn't seem to work. Something more needs to be done.

**Comment by lessthanoptimal** [comment]
Updated gradle to 7.3.3 which is what I'm using on most projects now. It builds but I've not tested it beyond that.

**Comment by apete** [comment]
Importing to eclipse works now, thanks.
