### ISSUE TITLE
Can't make directories to save results - error on Windows 7

### ISSUE THREAD

**Issue by Decrayer** [lessthanoptimal/Java-Matrix-Benchmark#8]
Hello,

I just tried to run the benchmark on windows 7, but I get the exception message "Can't make directories to save results" at jmbench.tools.runtime.RuntimeBenchmark.saveSystemInfo(RuntimeBenchmark.java:105)

Java version: jdk1.8.0_121

**Comment by lessthanoptimal** [comment]
Which branch of you running?  If you're not using the SNAPSHOT you should switch to that.  Also look at the readme/instructions.  Things have changed a bit.

**Comment by Decrayer** [comment]
I just downloaded the project here (on the 24th feb 2017) via the clone function as a zip file (master branch I guess, didn't see a SNAPSHOT branch though...)

I then followed the README.MD instructions, put Jeigen-onefat.jar and jna-4.1.0.jar into /external/jeigen/libs/, run "gradle createRuntimeJars", run "gradle benchmarkJar".

I run `java -jar benchmark.jar` and saw, that for running the runtime benchmark, I need to run

`java -jar benchmark.jar runtime` which I did.  The help section shows up and is confusing me. It tells me, that the only mandatory option is the `FixedMemory` one, which is not listed in the tool. The only memory setting that is listed is called `--Memory`, so I tried:

`java -jar benchmark.jar runtime --Memory=4096`

Which gives me the message:

> Exception in thread "main" java.lang.IllegalArgumentException: Can't make directories to save results.
>     at jmbench.tools.runtime.RuntimeBenchmark.saveSystemInfo<RuntimeBenchmark.java:105>
>     ...

**Comment by lessthanoptimal** [comment]
Think I found the error.  Windows doesn't like colons in file names right?  I was trying to create a directory with colons in the file name.  Pull the most recent version and see if that fixes it.

BTW your right that there's no SNAPSHOT.  Forgot that on this project I'm not doing that.  Probably because there isn't a stable version yet on git.

**Comment by Decrayer** [comment]
Alright, the new version is running fine now, issue is solved.

**Comment by lessthanoptimal** [comment]
I should add this to the documentation, but it takes a LONG time if you do the full benchmark.  10 days about.  --Quick cuts it down a lot.  I need to run that again to see how long it takes with the new code
